// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v7.36.2
// source: api_options.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export enum APISourceType {
  SOURCE_BOTH = 0,
  SOURCE_SERVER = 1,
  SOURCE_CLIENT = 2,
  UNRECOGNIZED = -1,
}

export function aPISourceTypeFromJSON(object: any): APISourceType {
  switch (object) {
    case 0:
    case "SOURCE_BOTH":
      return APISourceType.SOURCE_BOTH;
    case 1:
    case "SOURCE_SERVER":
      return APISourceType.SOURCE_SERVER;
    case 2:
    case "SOURCE_CLIENT":
      return APISourceType.SOURCE_CLIENT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return APISourceType.UNRECOGNIZED;
  }
}

export function aPISourceTypeToJSON(object: APISourceType): string {
  switch (object) {
    case APISourceType.SOURCE_BOTH:
      return "SOURCE_BOTH";
    case APISourceType.SOURCE_SERVER:
      return "SOURCE_SERVER";
    case APISourceType.SOURCE_CLIENT:
      return "SOURCE_CLIENT";
    case APISourceType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface voidMessage {
}

function createBasevoidMessage(): voidMessage {
  return {};
}

export const voidMessage: MessageFns<voidMessage> = {
  encode(_: voidMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): voidMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasevoidMessage();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): voidMessage {
    return {};
  },

  toJSON(_: voidMessage): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<voidMessage>, I>>(base?: I): voidMessage {
    return voidMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<voidMessage>, I>>(_: I): voidMessage {
    const message = createBasevoidMessage();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
